@startuml
box "AMP Page"
    participant AMPskimlinks as "amp-skimlinks"
end box

[-> AMPskimlinks: User visits AMP page.

==  whenBodyAvailable (DOM ready, can be pre-rendering phase) ==
hnote over AMPskimlinks: Register amp-skimlinks click handler
hnote over AMPskimlinks: Find links in page
AMPskimlinks -> BeaconAPI as "Beacon API \n (r.skimresources.com)": Request (GET): [domainA, domainB, domainC]?
note left
    Send all domains found in the
    page to beacon API to check
    which ones can be affiliated
end note
BeaconAPI --> AMPskimlinks: Response: [domainA, domainC]
hnote over AMPskimlinks: Update list of affiliate links
==  whenFirstVisible (page visible, actual rendering) ==
AMPskimlinks -> TrackingAPI as "Tracking API \n (t.skimresources.com)": Page impression tracking (POST): data={...}
TrackingAPI --> AMPskimlinks:
|||
AMPskimlinks -> TrackingAPI: Links impression tracking (POST): data={...}
TrackingAPI --> AMPskimlinks:

== On DOM changes ==
hnote over AMPskimlinks: DOM changes handler
AMPskimlinks -> BeaconAPI: Request (GET): [domainD, domainE]?
note left
    Send all **new** domains found in the
    page to Beacon API.
end note
BeaconAPI --> AMPskimlinks: Response: { DomainD: yes, domainE: false }
hnote over AMPskimlinks: Update list of affiliate links

== On anchor click ==
'IF
AMPskimlinks -> Waypoint as "Waypoint API \n (go.skimresources.com)": Navigate to waypoint url
note left AMPskimlinks #68b17a: **IF** link is AE
activate AMPskimlinks #68b17a
|||
Waypoint ->] : Redirect to merchant page
deactivate AMPskimlinks

|||

' ELSE
AMPskimlinks -> TrackingAPI: Track NA click
activate AMPskimlinks #orange
TrackingAPI --> AMPskimlinks
note left AMPskimlinks #orange: **ELSE** (NA)
|||
AMPskimlinks ->] : Navigate to url
deactivate AMPskimlinks

box "Skimlinks APIs" #LightBlue
	participant BeaconAPI
    participant TrackingAPI
    participant Waypoint
end box

@enduml